# Generated by Django 4.2.4 on 2023-08-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='background_image',
            field=models.ImageField(default=2, upload_to='home/', verbose_name='imagen de Fondo'),
            preserve_default=False,
        ),
    ]
