# Generated by Django 4.2.4 on 2024-02-22 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_articles_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='breaking_new',
            field=models.BooleanField(default=1, verbose_name='Ultima noticia'),
            preserve_default=False,
        ),
    ]
