# Generated by Django 4.2.4 on 2024-02-22 03:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_articles_breaking_new'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='News',
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Noticia', 'verbose_name_plural': 'Noticias'},
        ),
    ]
