# Generated by Django 4.2.4 on 2024-02-25 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Personal', 'verbose_name_plural': 'Personales'},
        ),
    ]
