# Generated by Django 4.2.4 on 2024-02-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='active',
            field=models.BooleanField(default=1, verbose_name='Activo'),
            preserve_default=False,
        ),
    ]
