# Generated by Django 4.2.4 on 2024-02-27 21:30

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_home_slug_news_slug_publicity_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('warp', models.CharField(max_length=100, verbose_name='Cintillo 1')),
                ('warp_2', models.CharField(max_length=100, verbose_name='Cintillo 2')),
                ('warp_3', models.CharField(max_length=100, verbose_name='Cintillo 3')),
            ],
            options={
                'verbose_name': 'Cintillo',
                'verbose_name_plural': 'Cintillos',
            },
        ),
    ]
