# Generated by Django 4.2.4 on 2024-02-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_warp'),
    ]

    operations = [
        migrations.AddField(
            model_name='warp',
            name='active',
            field=models.BooleanField(default=0, verbose_name='Activado'),
            preserve_default=False,
        ),
    ]
