# Generated by Django 4.2.4 on 2024-02-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_warp_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warp',
            name='warp_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cintillo 2'),
        ),
        migrations.AlterField(
            model_name='warp',
            name='warp_3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cintillo 3'),
        ),
    ]
