# Generated by Django 4.2.4 on 2024-02-23 02:22

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=20, verbose_name='Apellido')),
                ('avatar', models.ImageField(upload_to='team/', verbose_name='Foto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
