# Generated by Django 4.2.4 on 2024-02-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.RenameField(
            model_name='teams',
            old_name='image',
            new_name='image_31_28',
        ),
        migrations.AddField(
            model_name='teams',
            name='image_98_98',
            field=models.ImageField(blank=True, upload_to='Equipos/', verbose_name='Imagen'),
        ),
    ]
