# Generated by Django 4.2.4 on 2024-02-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_delete_team_rename_image_teams_image_31_28_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='image_31_28',
            field=models.ImageField(upload_to='Equipos/', verbose_name='Imagen de 31x28'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='image_98_98',
            field=models.ImageField(blank=True, upload_to='Equipos/', verbose_name='Imagen 98x98'),
        ),
    ]
