# Generated by Django 4.2.4 on 2024-02-25 16:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0004_alter_teams_image_31_28_alter_teams_image_98_98'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrincipalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('event', models.CharField(max_length=100, verbose_name='Evento')),
                ('description', models.TextField(verbose_name='descripcion')),
                ('date', models.DateTimeField(verbose_name='Fecha')),
                ('active', models.BooleanField(verbose_name='Activo')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_principal_event', to='sports.teams')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sports')),
                ('sport_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sportcategories')),
                ('visitor_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_principal_event', to='sports.teams')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
