# Generated by Django 4.2.4 on 2024-02-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0006_alter_principalevent_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='slug',
            field=models.CharField(blank=True, max_length=180, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='principalevent',
            name='slug',
            field=models.CharField(blank=True, max_length=180, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
