# Generated by Django 4.2.4 on 2024-02-21 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='rammer@rammerbot.com', max_length=254, verbose_name='Correo'),
            preserve_default=False,
        ),
    ]
